name = "ConnectionMatrices"
uuid = "94d474ba-9a8a-4612-aaf4-76c1836fe059"
authors = ["Thomas Wanner <twanner@gmu.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
